import Home from "./Home"
import Dashboard from "./Dashboard"
import Nav from "./Nav"
import Hero from "./Hero"
import Header from "./Header"
import Works from "./Works"
import Features from "./Features"
import Footer from "./Footer"
import Card from "./Card"
import Display from "./Display"
import Ready from "./Ready"
import Share from "./Share"
import Signup from "./Signup"

export { Home, Dashboard, Nav, Hero, Header, Works, Features, Footer, Card, Display, Ready, Share, Signup }